version: "3.5"

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_database_user
      - MYSQL_ROOT_PASSWORD=user_database_password
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/nest:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports: 
      - 8080:80
    environment:
      - PMA_ARBITRARY=1